"""Apply confirmed dirty-fact verdicts as soft-deletes.

This script is intentionally narrow:
- it reads a dirty candidate report generated by run_dirty_fact_candidates.py;
- it never physically deletes facts;
- it writes only when --yes is passed;
- it backs up the live DB with SQLite's backup API before writing;
- it updates facts.merged_into to the existing sentinel fact 999999.
"""

from __future__ import annotations

import argparse
import json
import sqlite3
import sys
import types
from datetime import datetime
from pathlib import Path
from typing import Any

PROJECT_ROOT = Path(__file__).absolute().parent.parent.parent
PARENT_DIR = PROJECT_ROOT.parent
if "" in sys.path:
    sys.path.remove("")
sys.path.insert(0, str(PARENT_DIR))

if "hermes_state" not in sys.modules:
    hermes_state = types.ModuleType("hermes_state")
    hermes_state.apply_wal_with_fallback = lambda conn, db_label="": None
    sys.modules["hermes_state"] = hermes_state

if "hermes_constants" not in sys.modules:
    hermes_constants = types.ModuleType("hermes_constants")
    hermes_constants.get_hermes_home = lambda: Path("C:/Users/sdses/AppData/Local/hermes")
    hermes_constants.display_hermes_home = lambda: "C:/Users/sdses/AppData/Local/hermes"
    sys.modules["hermes_constants"] = hermes_constants

if "agent.memory_provider" not in sys.modules:
    memory_provider = types.ModuleType("agent.memory_provider")

    class MemoryProvider:
        @property
        def name(self) -> str:
            return "stub"

    memory_provider.MemoryProvider = MemoryProvider
    sys.modules["agent.memory_provider"] = memory_provider
    sys.modules.setdefault("agent", types.ModuleType("agent"))

if "tools.registry" not in sys.modules:
    tools_registry = types.ModuleType("tools.registry")
    tools_registry.tool_error = lambda message: f"ERROR: {message}"
    sys.modules["tools.registry"] = tools_registry
    sys.modules.setdefault("tools", types.ModuleType("tools"))

if "hermes_cli.config" not in sys.modules:
    hermes_cli_config = types.ModuleType("hermes_cli.config")

    def _cfg_get(config: dict, *keys: str, default=None):
        current = config
        for key in keys:
            if not isinstance(current, dict) or key not in current:
                return default
            current = current[key]
        return current if current is not None else default

    hermes_cli_config.cfg_get = _cfg_get
    sys.modules["hermes_cli.config"] = hermes_cli_config
    sys.modules.setdefault("hermes_cli", types.ModuleType("hermes_cli"))

from holographic.store import MemoryStore  # noqa: E402


SOFT_DELETE_SENTINEL = 999999


def _default_db_path() -> Path:
    return Path("C:/Users/sdses/AppData/Local/hermes/memory_store.db")


def load_report(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def selected_fact_ids(
    report: dict[str, Any],
    *,
    apply_likely_dirty: bool,
    verdicts: set[str],
) -> list[int]:
    fact_ids: list[int] = []
    for item in report.get("candidates", []):
        verdict = str(item.get("verdict", "")).strip().lower()
        disposition = str(item.get("disposition", "")).strip().lower()
        if verdict and verdict in verdicts:
            fact_ids.append(int(item["fact_id"]))
        elif apply_likely_dirty and disposition == "likely_dirty":
            fact_ids.append(int(item["fact_id"]))
    return list(dict.fromkeys(fact_ids))


def create_backup(source: Path, backup_dir: Path) -> Path:
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    backup_dir.mkdir(parents=True, exist_ok=True)
    backup_path = backup_dir / f"memory_store_before_dirty_apply_{timestamp}.db"

    src = sqlite3.connect(str(source))
    try:
        src.execute("PRAGMA wal_checkpoint(FULL)")
        dst = sqlite3.connect(str(backup_path))
        try:
            src.backup(dst)
        finally:
            dst.close()
    finally:
        src.close()
    return backup_path


def _fetch_count(conn: sqlite3.Connection, query: str, params: tuple[Any, ...] = ()) -> int:
    row = conn.execute(query, params).fetchone()
    return int(row[0]) if row else 0


def preview(db_path: Path, fact_ids: list[int]) -> dict[str, Any]:
    conn = sqlite3.connect(str(db_path))
    conn.row_factory = sqlite3.Row
    try:
        if fact_ids:
            placeholders = ",".join("?" for _ in fact_ids)
            rows = [
                dict(row)
                for row in conn.execute(
                    f"""
                    SELECT fact_id, content, category, source_doc_id, merged_into
                    FROM facts
                    WHERE fact_id IN ({placeholders})
                    ORDER BY fact_id
                    """,
                    tuple(fact_ids),
                )
            ]
        else:
            rows = []
        return {
            "facts_total": _fetch_count(conn, "SELECT COUNT(*) FROM facts"),
            "facts_active": _fetch_count(conn, "SELECT COUNT(*) FROM facts WHERE merged_into IS NULL"),
            "facts_soft_deleted": _fetch_count(
                conn, "SELECT COUNT(*) FROM facts WHERE merged_into IS NOT NULL"
            ),
            "selected": rows,
            "sentinel_exists": bool(
                conn.execute(
                    "SELECT 1 FROM facts WHERE fact_id = ?",
                    (SOFT_DELETE_SENTINEL,),
                ).fetchone()
            ),
        }
    finally:
        conn.close()


def apply_soft_delete(db_path: Path, fact_ids: list[int]) -> dict[str, Any]:
    if not fact_ids:
        return {"updated": 0, "categories": []}

    conn = sqlite3.connect(str(db_path))
    conn.row_factory = sqlite3.Row
    try:
        conn.execute("BEGIN IMMEDIATE")
        sentinel = conn.execute(
            "SELECT 1 FROM facts WHERE fact_id = ?",
            (SOFT_DELETE_SENTINEL,),
        ).fetchone()
        if sentinel is None:
            raise RuntimeError(f"soft-delete sentinel fact {SOFT_DELETE_SENTINEL} does not exist")

        placeholders = ",".join("?" for _ in fact_ids)
        rows = [
            dict(row)
            for row in conn.execute(
                f"""
                SELECT fact_id, category, merged_into
                FROM facts
                WHERE fact_id IN ({placeholders})
                ORDER BY fact_id
                """,
                tuple(fact_ids),
            )
        ]
        found_ids = {int(row["fact_id"]) for row in rows}
        missing = [fact_id for fact_id in fact_ids if fact_id not in found_ids]
        if missing:
            raise RuntimeError(f"selected fact IDs not found: {missing}")

        already_deleted = [int(row["fact_id"]) for row in rows if row["merged_into"] is not None]
        if already_deleted:
            raise RuntimeError(f"selected fact IDs are already soft-deleted: {already_deleted}")

        categories = sorted({str(row["category"]) for row in rows})
        cur = conn.execute(
            f"""
            UPDATE facts
            SET merged_into = ?, updated_at = CURRENT_TIMESTAMP
            WHERE fact_id IN ({placeholders})
              AND merged_into IS NULL
            """,
            (SOFT_DELETE_SENTINEL, *fact_ids),
        )
        updated = int(cur.rowcount)
        conn.commit()
        return {"updated": updated, "categories": categories}
    except Exception:
        conn.rollback()
        raise
    finally:
        conn.close()


def rebuild_banks(db_path: Path, categories: list[str]) -> None:
    if not categories:
        return
    store = MemoryStore(db_path=str(db_path))
    try:
        for category in categories:
            store._rebuild_bank(category)
    finally:
        store.close()


def write_apply_report(report: dict[str, Any], output_dir: Path) -> tuple[Path, Path]:
    output_dir.mkdir(parents=True, exist_ok=True)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    json_path = output_dir / f"dirty_fact_apply_{timestamp}.json"
    md_path = output_dir / f"dirty_fact_apply_{timestamp}.md"
    json_path.write_text(json.dumps(report, ensure_ascii=False, indent=2), encoding="utf-8")

    lines = [
        "# Dirty Fact Apply Report",
        "",
        f"- generated_at: {report['generated_at']}",
        f"- dry_run: {report['dry_run']}",
        f"- db: `{report['db']}`",
        f"- candidate_report: `{report['candidate_report']}`",
        f"- backup: `{report.get('backup') or ''}`",
        f"- selected_count: {len(report['selected_fact_ids'])}",
        f"- updated: {report['apply_result'].get('updated', 0)}",
        f"- active_before: {report['before']['facts_active']}",
        f"- active_after: {report['after']['facts_active']}",
        f"- soft_deleted_before: {report['before']['facts_soft_deleted']}",
        f"- soft_deleted_after: {report['after']['facts_soft_deleted']}",
        "",
        "| fact_id | category | doc | content |",
        "|---:|---|---:|---|",
    ]
    for row in report["before"]["selected"]:
        content = str(row["content"]).replace("|", "\\|").replace("\n", " ")
        lines.append(f"| {row['fact_id']} | {row['category']} | {row['source_doc_id']} | {content} |")
    md_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return json_path, md_path


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--db", type=Path, default=_default_db_path())
    parser.add_argument("--report", type=Path, default=Path("reports/dirty_fact_candidates.json"))
    parser.add_argument("--output-dir", type=Path, default=Path("reports"))
    parser.add_argument("--backup-dir", type=Path, default=Path("reports/live_backups"))
    parser.add_argument("--apply-likely-dirty", action="store_true")
    parser.add_argument("--verdict", action="append", default=["reject", "dirty"])
    parser.add_argument("--yes", action="store_true")
    args = parser.parse_args()

    candidate_report = load_report(args.report)
    fact_ids = selected_fact_ids(
        candidate_report,
        apply_likely_dirty=args.apply_likely_dirty,
        verdicts={str(v).strip().lower() for v in args.verdict},
    )

    before = preview(args.db, fact_ids)
    if not before["sentinel_exists"]:
        raise RuntimeError(f"soft-delete sentinel fact {SOFT_DELETE_SENTINEL} does not exist")

    backup_path: Path | None = None
    apply_result = {"updated": 0, "categories": []}
    if args.yes:
        backup_path = create_backup(args.db, args.backup_dir)
        apply_result = apply_soft_delete(args.db, fact_ids)
        rebuild_banks(args.db, apply_result["categories"])

    after = preview(args.db, fact_ids)
    apply_report = {
        "generated_at": datetime.now().isoformat(timespec="seconds"),
        "dry_run": not args.yes,
        "db": str(args.db),
        "candidate_report": str(args.report),
        "backup": str(backup_path) if backup_path else None,
        "selected_fact_ids": fact_ids,
        "before": before,
        "after": after,
        "apply_result": apply_result,
    }
    json_path, md_path = write_apply_report(apply_report, args.output_dir)

    print(f"dry_run={not args.yes}")
    print(f"selected_count={len(fact_ids)}")
    print(f"updated={apply_result.get('updated', 0)}")
    print(f"backup={backup_path}")
    print(f"json={json_path}")
    print(f"markdown={md_path}")
    print(f"active_before={before['facts_active']}")
    print(f"active_after={after['facts_active']}")


if __name__ == "__main__":
    main()
